
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUyLCJpYXQiOjE2MzI0ODk4NjUsImV4cCI6MTYzMjQ5MzQ2NX0.ljaQRuN8eNJVBsqND7KkPBQk436K3T4JIgiTv7qYsIU

###

GET http://localhost:5000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUyLCJpYXQiOjE2MzI0ODk4NjUsImV4cCI6MTYzMjQ5MzQ2NX0.ljaQRuN8eNJVBsqND7KkPBQk436K3T4JIgiTv7qYsIU



###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username":"ert",
    "password":"ert"
    
}