
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVydCIsImlhdCI6MTYzMTgxODYzMH0.BSChDI7NHdr52LBu7DAJE4R4n49EoC9zhAwDep-c_gE


###
POST http://localhost:5000/api/token
Content-Type: application/json

{
    "username":"ert",
    "password":"ert"
    
}