GET http://localhost:5000/api/users
###

POST http://localhost:5000/api/token
Content-Type: application/json

{
    "username":"ert",
    "password":"ert"
}
###
POST http://localhost:5000/api/auth
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVydCIsImlhdCI6MTYzMTcyNjQzMn0.2dGqZKoBLcWyYybM9G0vDb_ay3hR2QDiYOMSTkA8FCo
